version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_filament_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        # depends_on:
        #     - redis
        networks:
            - laravel

    # nginx
    nginx:
        container_name: laravel_webserver_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8787:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        container_name: laravel_filament_db
        image: mysql:8.0.41
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3344:3306"
        networks:
            - laravel
    # # queue
    # queue:
    #     image: especializati/laravel9-app
    #     restart: unless-stopped
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./:/var/www
    #     depends_on:
    #         - redis
    #         - app
    #     networks:
    #         - laravel

    # # redis
    # redis:
    #     image: redis:latest
    #     networks:
    #         - laravel

networks:
    laravel:
        driver: bridge
